// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotyB3Igx8xbJFLL555qDQvaHN-QqCBM4',
    appId: '1:565296337949:web:3af8f909385b05cc70e2f4',
    messagingSenderId: '565296337949',
    projectId: 'telabang-mandau-e8030',
    authDomain: 'telabang-mandau-e8030.firebaseapp.com',
    storageBucket: 'telabang-mandau-e8030.firebasestorage.app',
    measurementId: 'G-WHWBVCYCR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7DYCNCjv2jcu34rZnGpXmD_kofH0B8C0',
    appId: '1:565296337949:android:f8ae9be6edc2be9170e2f4',
    messagingSenderId: '565296337949',
    projectId: 'telabang-mandau-e8030',
    storageBucket: 'telabang-mandau-e8030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHTm_VxPaccoSZ2AwvlELMGcQjLlE4d4',
    appId: '1:565296337949:ios:b2e2e692c8aeef0470e2f4',
    messagingSenderId: '565296337949',
    projectId: 'telabang-mandau-e8030',
    storageBucket: 'telabang-mandau-e8030.firebasestorage.app',
    iosBundleId: 'com.talabang.talabangMandau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHTm_VxPaccoSZ2AwvlELMGcQjLlE4d4',
    appId: '1:565296337949:ios:b2e2e692c8aeef0470e2f4',
    messagingSenderId: '565296337949',
    projectId: 'telabang-mandau-e8030',
    storageBucket: 'telabang-mandau-e8030.firebasestorage.app',
    iosBundleId: 'com.talabang.talabangMandau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDotyB3Igx8xbJFLL555qDQvaHN-QqCBM4',
    appId: '1:565296337949:web:40c071711855bfb270e2f4',
    messagingSenderId: '565296337949',
    projectId: 'telabang-mandau-e8030',
    authDomain: 'telabang-mandau-e8030.firebaseapp.com',
    storageBucket: 'telabang-mandau-e8030.firebasestorage.app',
    measurementId: 'G-GQ6YFDEDHW',
  );

}